export interface CatalogEntry { id: string; symbol: string; name: string }

export const CATALOG: CatalogEntry[] = [
  // ── Layer 1 ──────────────────────────────────────────────────────────────
  { id: "bitcoin",                   symbol: "BTC",    name: "Bitcoin"             },
  { id: "ethereum",                  symbol: "ETH",    name: "Ethereum"            },
  { id: "binancecoin",               symbol: "BNB",    name: "BNB"                 },
  { id: "ripple",                    symbol: "XRP",    name: "XRP"                 },
  { id: "solana",                    symbol: "SOL",    name: "Solana"              },
  { id: "cardano",                   symbol: "ADA",    name: "Cardano"             },
  { id: "dogecoin",                  symbol: "DOGE",   name: "Dogecoin"            },
  { id: "tron",                      symbol: "TRX",    name: "TRON"                },
  { id: "avalanche-2",               symbol: "AVAX",   name: "Avalanche"           },
  { id: "the-open-network",          symbol: "TON",    name: "Toncoin"             },
  { id: "polkadot",                  symbol: "DOT",    name: "Polkadot"            },
  { id: "bitcoin-cash",              symbol: "BCH",    name: "Bitcoin Cash"        },
  { id: "near",                      symbol: "NEAR",   name: "NEAR Protocol"       },
  { id: "litecoin",                  symbol: "LTC",    name: "Litecoin"            },
  { id: "internet-computer",         symbol: "ICP",    name: "Internet Computer"   },
  { id: "aptos",                     symbol: "APT",    name: "Aptos"               },
  { id: "sui",                       symbol: "SUI",    name: "Sui"                 },
  { id: "ethereum-classic",          symbol: "ETC",    name: "Ethereum Classic"    },
  { id: "cosmos",                    symbol: "ATOM",   name: "Cosmos"              },
  { id: "hedera-hashgraph",          symbol: "HBAR",   name: "Hedera"              },
  { id: "stellar",                   symbol: "XLM",    name: "Stellar"             },
  { id: "monero",                    symbol: "XMR",    name: "Monero"              },
  { id: "kaspa",                     symbol: "KAS",    name: "Kaspa"               },
  { id: "vechain",                   symbol: "VET",    name: "VeChain"             },
  { id: "eos",                       symbol: "EOS",    name: "EOS"                 },
  { id: "algorand",                  symbol: "ALGO",   name: "Algorand"            },
  { id: "dash",                      symbol: "DASH",   name: "Dash"                },
  { id: "zcash",                     symbol: "ZEC",    name: "Zcash"               },
  { id: "iota",                      symbol: "MIOTA",  name: "IOTA"                },
  { id: "neo",                       symbol: "NEO",    name: "Neo"                 },
  { id: "fantom",                    symbol: "FTM",    name: "Fantom"              },
  { id: "elrond-erd-2",              symbol: "EGLD",   name: "MultiversX"          },
  { id: "harmony",                   symbol: "ONE",    name: "Harmony"             },
  { id: "kava",                      symbol: "KAVA",   name: "Kava"                },
  { id: "bittensor",                 symbol: "TAO",    name: "Bittensor"           },
  { id: "ronin",                     symbol: "RON",    name: "Ronin"               },
  { id: "ondo-finance",              symbol: "ONDO",   name: "Ondo"                },
  { id: "bitcoin-sv",                symbol: "BSV",    name: "Bitcoin SV"          },
  { id: "waves",                     symbol: "WAVES",  name: "Waves"               },
  { id: "zilliqa",                   symbol: "ZIL",    name: "Zilliqa"             },
  { id: "icon",                      symbol: "ICX",    name: "ICON"                },
  { id: "ontology",                  symbol: "ONT",    name: "Ontology"            },
  { id: "conflux-token",             symbol: "CFX",    name: "Conflux"             },
  { id: "kusama",                    symbol: "KSM",    name: "Kusama"              },
  { id: "zencash",                   symbol: "ZEN",    name: "Horizen"             },
  // ── Layer 2 / Scaling ────────────────────────────────────────────────────
  { id: "matic-network",             symbol: "POL",    name: "Polygon"             },
  { id: "arbitrum",                  symbol: "ARB",    name: "Arbitrum"            },
  { id: "optimism",                  symbol: "OP",     name: "Optimism"            },
  { id: "starknet",                  symbol: "STRK",   name: "Starknet"            },
  { id: "immutable-x",               symbol: "IMX",    name: "Immutable"           },
  { id: "mantle",                    symbol: "MNT",    name: "Mantle"              },
  { id: "loopring",                  symbol: "LRC",    name: "Loopring"            },
  { id: "metis-token",               symbol: "METIS",  name: "Metis"               },
  { id: "stacks",                    symbol: "STX",    name: "Stacks"              },
  // ── DeFi ─────────────────────────────────────────────────────────────────
  { id: "chainlink",                 symbol: "LINK",   name: "Chainlink"           },
  { id: "uniswap",                   symbol: "UNI",    name: "Uniswap"             },
  { id: "aave",                      symbol: "AAVE",   name: "Aave"                },
  { id: "maker",                     symbol: "MKR",    name: "Maker"               },
  { id: "curve-dao-token",           symbol: "CRV",    name: "Curve"               },
  { id: "compound-governance-token", symbol: "COMP",   name: "Compound"            },
  { id: "yearn-finance",             symbol: "YFI",    name: "yearn.finance"       },
  { id: "synthetix-network-token",   symbol: "SNX",    name: "Synthetix"           },
  { id: "lido-dao",                  symbol: "LDO",    name: "Lido DAO"            },
  { id: "pancakeswap-token",         symbol: "CAKE",   name: "PancakeSwap"         },
  { id: "1inch",                     symbol: "1INCH",  name: "1inch"               },
  { id: "sushi",                     symbol: "SUSHI",  name: "SushiSwap"           },
  { id: "balancer",                  symbol: "BAL",    name: "Balancer"            },
  { id: "dydx-chain",                symbol: "DYDX",   name: "dYdX"               },
  { id: "gmx",                       symbol: "GMX",    name: "GMX"                 },
  { id: "pendle",                    symbol: "PENDLE", name: "Pendle"              },
  { id: "thorchain",                 symbol: "RUNE",   name: "THORChain"           },
  { id: "the-graph",                 symbol: "GRT",    name: "The Graph"           },
  { id: "injective-protocol",        symbol: "INJ",    name: "Injective"           },
  { id: "convex-finance",            symbol: "CVX",    name: "Convex Finance"      },
  { id: "blur",                      symbol: "BLUR",   name: "Blur"                },
  { id: "ethena",                    symbol: "ENA",    name: "Ethena"              },
  { id: "hyperliquid",               symbol: "HYPE",   name: "Hyperliquid"         },
  { id: "raydium",                   symbol: "RAY",    name: "Raydium"             },
  { id: "jupiter-exchange-solana",   symbol: "JUP",    name: "Jupiter"             },
  { id: "jito-governance-token",     symbol: "JTO",    name: "Jito"                },
  { id: "ethereum-name-service",     symbol: "ENS",    name: "ENS"                 },
  { id: "bounce-token",              symbol: "AUCTION",name: "Auction"             },
  // ── AI / Data / Infra ────────────────────────────────────────────────────
  { id: "fetch-ai",                  symbol: "FET",    name: "Fetch.ai"            },
  { id: "render-token",              symbol: "RENDER", name: "Render"              },
  { id: "worldcoin-wld",             symbol: "WLD",    name: "Worldcoin"           },
  { id: "ocean-protocol",            symbol: "OCEAN",  name: "Ocean Protocol"      },
  { id: "grass",                     symbol: "GRASS",  name: "Grass"               },
  { id: "io-net",                    symbol: "IO",     name: "io.net"              },
  { id: "akash-network",             symbol: "AKT",    name: "Akash Network"       },
  { id: "singularitynet",            symbol: "AGIX",   name: "SingularityNET"      },
  { id: "pyth-network",              symbol: "PYTH",   name: "Pyth Network"        },
  { id: "wormhole",                  symbol: "W",      name: "Wormhole"            },
  { id: "celestia",                  symbol: "TIA",    name: "Celestia"            },
  { id: "eigenlayer",                symbol: "EIGEN",  name: "EigenLayer"          },
  { id: "filecoin",                  symbol: "FIL",    name: "Filecoin"            },
  { id: "helium",                    symbol: "HNT",    name: "Helium"              },
  { id: "storj",                     symbol: "STORJ",  name: "Storj"               },
  { id: "golem",                     symbol: "GLM",    name: "Golem"               },
  { id: "ankr",                      symbol: "ANKR",   name: "Ankr"                },
  { id: "arweave",                   symbol: "AR",     name: "Arweave"             },
  { id: "livepeer",                  symbol: "LPT",    name: "Livepeer"            },
  { id: "virtual-protocol",          symbol: "VIRTUAL",name: "Virtuals Protocol"   },
  { id: "ssv-network",               symbol: "SSV",    name: "SSV Network"         },
  // ── Oracles / Middleware ──────────────────────────────────────────────────
  { id: "basic-attention-token",     symbol: "BAT",    name: "Basic Attention"     },
  { id: "0x",                        symbol: "ZRX",    name: "0x Protocol"         },
  { id: "band-protocol",             symbol: "BAND",   name: "Band Protocol"       },
  { id: "api3",                      symbol: "API3",   name: "API3"                },
  { id: "tellor",                    symbol: "TRB",    name: "Tellor"              },
  { id: "numeraire",                 symbol: "NMR",    name: "Numeraire"           },
  { id: "uma",                       symbol: "UMA",    name: "UMA"                 },
  // ── Gaming / NFT / Metaverse ─────────────────────────────────────────────
  { id: "axie-infinity",             symbol: "AXS",    name: "Axie Infinity"       },
  { id: "decentraland",              symbol: "MANA",   name: "Decentraland"        },
  { id: "the-sandbox",               symbol: "SAND",   name: "The Sandbox"         },
  { id: "gala",                      symbol: "GALA",   name: "Gala"                },
  { id: "flow",                      symbol: "FLOW",   name: "Flow"                },
  { id: "theta-token",               symbol: "THETA",  name: "Theta"               },
  { id: "enjincoin",                 symbol: "ENJ",    name: "Enjin Coin"          },
  { id: "chiliz",                    symbol: "CHZ",    name: "Chiliz"              },
  { id: "illuvium",                  symbol: "ILV",    name: "Illuvium"            },
  { id: "gods-unchained",            symbol: "GODS",   name: "Gods Unchained"      },
  { id: "superfarm",                 symbol: "SUPER",  name: "SuperVerse"          },
  { id: "apecoin",                   symbol: "APE",    name: "ApeCoin"             },
  // ── Memes ────────────────────────────────────────────────────────────────
  { id: "shiba-inu",                 symbol: "SHIB",   name: "Shiba Inu"           },
  { id: "pepe",                      symbol: "PEPE",   name: "Pepe"                },
  { id: "bonk",                      symbol: "BONK",   name: "Bonk"               },
  { id: "dogwifcoin",                symbol: "WIF",    name: "dogwifhat"           },
  { id: "floki",                     symbol: "FLOKI",  name: "Floki"               },
  { id: "cat-in-a-dogs-world",       symbol: "MEW",    name: "cat in a dogs world" },
  { id: "book-of-meme",              symbol: "BOME",   name: "Book of Meme"        },
  { id: "mog-coin",                  symbol: "MOG",    name: "Mog Coin"            },
  { id: "brett",                     symbol: "BRETT",  name: "Brett"               },
  { id: "degen-base",                symbol: "DEGEN",  name: "Degen"               },
  { id: "popcat",                    symbol: "POPCAT", name: "Popcat"              },
  { id: "dogs-token",                symbol: "DOGS",   name: "DOGS"                },
  { id: "notcoin",                   symbol: "NOT",    name: "Notcoin"             },
  { id: "baby-doge-coin",            symbol: "BABYDOGE",name: "Baby Doge Coin"     },
  { id: "official-trump",            symbol: "TRUMP",  name: "Official Trump"      },
  { id: "memecoin",                  symbol: "MEME",   name: "Memecoin"            },
  { id: "ordinals",                  symbol: "ORDI",   name: "ORDI"                },
  // ── Ecosystem / Misc ─────────────────────────────────────────────────────
  { id: "sei-network",               symbol: "SEI",    name: "Sei"                 },
  { id: "berachain-bera",            symbol: "BERA",   name: "Berachain"           },
  { id: "rocket-pool",               symbol: "RPL",    name: "Rocket Pool"         },
  { id: "nervos-network",            symbol: "CKB",    name: "Nervos Network"      },
  { id: "qtum",                      symbol: "QTUM",   name: "Qtum"                },
];
